### ISSUE TITLE
adjust() does not work properly

### ISSUE THREAD

**Issue by jey1401** [rcs333/VAPiD#5]
Minimally reproducible example:
```
>>> import vapid
>>> d = vapid.build_num_arrays("a--g-", "accgt")
>>> vapid.adjust(2, d[0], d[1], "accgt")
'-1'
```

**Comment by rcs333** [comment]
This is actually intentional behavior, the second character is not an alignment match so we return -1 as an error code to let me know that the alignment isn't matching at that location.
